base_dir: /eos/uscms/store/group/lpcsusylep/anazario/LLPSkims/skims_v49

lumi: 138.0
energy: 13.
analysis_type: compressed
isr_pt_cut: 800
plots: [ratio]
format: [pdf,root]
output: datamc_promptpho_compressed_v49

# CR-only prompt photon selection:
# - nBaseLinePhotons >= 1
# - all baseline photons satisfy |baseLinePhoton_WTimeSig| < 2.5
# - all baseline photons satisfy baseLinePhoton_isoANNScore < 0.96
flags:
  - cut: "PROMPT_PHO_CR_COMPRESSED_GE1"
    region_type: pho

signal:
  - SMS_SVHPM100_v34_gogoGZ_FULLMINI_mGl-2500_mN2-1200_mN1-500_ct0p1_rjrskim.root

background:
  - name: W+jets
    files:
      - background/WJets.root
  - name: Z+jets
    files:
      - background/ZJets.root
  - name: t#bar{t}+jets
    scale: 1.
    files:
      - background/TTJets.root
  - name: "#gamma+jets"
    scale: 1.
    files:
      - background/GJets.root
      - background/QCD.root
data:
  - name: Run 2+3
    combine: true
    files:
      - data/MET_Run2016.root
      - data/MET_Run2017.root
      - data/MET_Run2018.root
